[versions]
compileSdk = "33"
gradleNexusStagingPlugin = "0.30.0"
minSdk = "21"
targetSdk = "33"
ktlint = "0.42.1"

composeBom = "2023.04.00"
composeCompiler = '1.4.5'
gradle = "8.0.0"
kotlin = "1.8.20"

activityComposeVersion = "1.3.1"
lifecycleRuntimeKtxVersion = "2.3.1"

spotless = "6.21.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
nexus-staging = { id = 'io.codearte.nexus-staging', version.ref = "gradleNexusStagingPlugin" }